.TH PYUWU 1
.SH NAME
py2uwu \- Translate python files to pyuwu
.SH SYNOPSIS
.B py2uwu
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B py2uwu
is a program that translates regular python scripts to pyuwu
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.BR \-v ", " \-\-version
Show version number and exit.
.TP
.BR \-o ", " \-\-output
Specify the name of output file.
.SH SEE ALSO
pyuwu(1)
.SH AUTHOR
Shamith Pasula 2024
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/shamith09/pyuwu/blob/master/LICENSE



