.TH PYUWU 1
.SH NAME
by2py \- Translate pyuwu files to python
.SH SYNOPSIS
.B uwu2py
[\fIFLAGS\fR]
.IR scriptfile
.SH DESCRIPTION
.B uwu2py
is an alias for 'pyuwu -c'. For more information, look up the manual for pyuwu(1).
.SH SEE ALSO
pyuwu(1)
.SH AUTHOR
Shamith Pasula 2024
.SH LICENSE
This program is licensed under the MIT license. See [1] for details. TL;DR: Do whatever you want as long as you include the original copyright and license notice.
.TP
[1]
https://github.com/shamith09/pyuwu/blob/master/LICENSE



